### ISSUE TITLE
privacyIDEA URL is not showing with keycloak account2 preview features in admin console setting

### ISSUE THREAD

**Issue by sayedcsekuet** [privacyidea/keycloak-provider#102]
Hi,
I was trying to enable keycloak account2 preview feature. In privacyidea config setup privacyIDEA URL field is not visible.

**Comment by sayedcsekuet** [comment]
Hi,
@lukasmatusiewicz  Sorry for my bad english. After enabling account2 features (new keycloak ui console) in keycloak 18, I was trying to configure privacyidea setting, I saw that privacyIdea url field is not appearing but all other fields are visible the setting page. Please see in the image there is no "PrivacyIDEA URL" field.
![Screenshot 2022-06-13 at 17 43 46](https://user-images.githubusercontent.com/728503/173393092-71146829-7d7e-4837-b982-75656535c625.png)

**Comment by nilsbehlen** [comment]
Hi, we will need some more time to reproduce this setup.
Meanwhile you can try this version
[PrivacyIDEA-Provider-v1.0.2pre.jar.zip](https://github.com/privacyidea/keycloak-provider/files/8900582/PrivacyIDEA-Provider-v1.0.2pre.jar.zip)
to see if it fixes the problem.

**Comment by sayedcsekuet** [comment]
@nilsbehlen Thanks for your information. I will try.

**Comment by lukasmatusiewicz** [comment]
Hi @sayedcsekuet ,

I have dug a little for that and as KC documentation says account2 is enabled by default. I have enabled it even so and it works for me just normally how it was. Have you tested this jar that @nilsbehlen send you? Are you sure that this problem occurs exactly after enabling account2 and doesn't occurred before? Have you tried it in another browser?

Greets

**Comment by sayedcsekuet** [comment]
Hi @lukasmatusiewicz,
Sorry for late answer, was sick. I have tested your version, it's working fine. You are right account2 is enabled by default.
