### ISSUE TITLE
Manual build with source code - Fails

### ISSUE THREAD

**Issue by arozmarin** [privacyidea/keycloak-provider#103]
Hi guys, 

I try to manual build plugin and I always get an error:

[ERROR] Failed to execute goal on project privacyidea-keycloak-provider: Could not resolve dependencies for project org.privacyidea:privacyidea-keycloak-provider:jar:1.0.1: Failure to find org.privacyidea:privacyidea-java-client:jar:1.0.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I run man test 

[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.privacyidea:privacyidea-keycloak-provider >------------
[INFO] Building privacyidea-keycloak-provider 1.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.privacyidea:privacyidea-java-client:jar:1.0.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.697 s
[INFO] Finished at: 2022-05-19T12:42:47+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project privacyidea-keycloak-provider: Could not resolve dependencies for project org.privacyidea:privacyidea-keycloak-provider:jar:1.0.1: Failure to find org.privacyidea:privacyidea-java-client:jar:1.0.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Any idea what I'm doing wrong here? Any tip would help

thanks

**Comment by nilsbehlen** [comment]
Hi, the error is this:
` Failure to find org.privacyidea:privacyidea-java-client:jar:1.0.2 `
Which means you have to build the java-client first. It is located in `\java-client`. There you have to do `mvn clean install`.

**Comment by arozmarin** [comment]
thanks for help nilsbehlen

it worked now :)
