### ISSUE TITLE
Subgroups in Included groups.

### ISSUE THREAD

**Issue by jkovaliov** [privacyidea/keycloak-provider#110]
Hello, is it possible for subgroups users to be included in 2FA by entering only the master group into the “Included groups” field? Or it is required to name all of them altogether groups and every subgroup in that field?

**Comment by lukasmatusiewicz** [comment]
Hi @jkovaliov, as I see subgroups are since KC18. 'Included groups' was made with KC17. I'll check it and let you know soon. Have you already tried to do it without success?

**Comment by lukasmatusiewicz** [comment]
So I have tested it. Every child group inherits from "included groups" in this situation and will be joined to included automatically. You don't have to add every subgroup to the list. Btw. good lifehack:)
