### ISSUE TITLE
[Keycloak] Enroll Push Token

### ISSUE THREAD

**Issue by KeycloakBoys** [privacyidea/keycloak-provider#118]
Could it be possibile to add to 'Enrollment token type' the Push type?

**Comment by lukasmatusiewicz** [comment]
Right now, Push token enrollment is possible only in the privacyIDEA. But the enrollment process will be improved soon and this enhancement is also planned, so stay tuned!

**Comment by KeycloakBoys** [comment]
OK Thank You!
