### ISSUE TITLE
[Keycloak] Enroll TOTP from Keycloak does not work

### ISSUE THREAD

**Issue by KeycloakBoys** [privacyidea/keycloak-provider#120]
Hi, 

We configured PrivacyIdea Server for Push, but we wanted to try TOTP too.
We are experiencing 'Authentication failed. wrong otp pin' errors if we enroll from keycloak.
Instead if we configure TOTP from PrivacyIdea everything goes correctly.

**TOTP enrolled from keycloak:**

2022-11-30 11:17:03,553 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (OkHttp https:///...) PrivacyIDEA Client: /validate/check:
{
  "detail": {
    "message": "wrong otp pin",
    "threadid": 140615254603584
  },
  "id": 2,
  "jsonrpc": "2.0",
  "result": {
    "authentication": "REJECT",
    "status": true,
    "value": false
  },
  "time": 1669803423.5127044,
  "version": "privacyIDEA 3.7.4",
  "versionnumber": "3.7.4",

**TOTP enrolled from PrivacyIDEA:**

{
  "detail": {
    "message": "Found matching challenge",
    "serial": "TOTP00004B34",
    "threadid": 140615254603584
  },
  "id": 2,
  "jsonrpc": "2.0",
  "result": {
    "authentication": "ACCEPT",
    "status": true,
    "value": true
  },
  "time": 1669803507.1315897,
  "version": "privacyIDEA 3.7.4",
  "versionnumber": "3.7.4",

Keycloak Plugin Configuration:
![Keycloak-PrivacyIdea-Plugin](https://user-images.githubusercontent.com/119416997/204771263-4a6b3189-4542-43ad-b0fb-bf2975cc9aa0.png)

Enroll by Keycloak:
![enroll](https://user-images.githubusercontent.com/119416997/204771681-5f834aa7-d00f-44d9-b6c3-c210a94eca2d.png)

Error:
![error](https://user-images.githubusercontent.com/119416997/204771709-45da03d9-38ca-4a3b-b7e4-972c94ab73d6.png)

Could anyone help us? Thank You!

**Comment by lukasmatusiewicz** [comment]
For help with settings or policies, please visit the community site:
#125
