### ISSUE TITLE
Add preferred token type

### ISSUE THREAD

**Issue by lukasmatusiewicz** [privacyidea/keycloak-provider#121]
If in response from the server exists `preferred_client_mode` use it to replace the `preferredTokenType` option in the future.

NOTE: Leave booth options for some time, but if `preferred_client_mode` is found in response use it and ignore the old option.

@nilsbehlen should we already inform the user in a debug message about this future change, and recommend using the new method?

**Comment by nilsbehlen** [comment]
The user will not see any debug messages, it would be the admin. I dont think we need to make this kind of investment, just add in docs that the option in the plugin will be deprecated in the future and also write this in the patch notes.
