### ISSUE TITLE
Poll in browser

### ISSUE THREAD

**Issue by lukasmatusiewicz** [privacyidea/keycloak-provider#133]
Process the poll transaction (push mode) in the background instead of continuously submitting the form.

Perform a poll transaction in the browser and repeat it until `response->result->value === true`.
If success -> submit form and perform the validate/check request.

**Comment by gryffus** [comment]
Hello,

since PA now supports token-decline message [1], would be possible to implement this also in this plugin?

Is it in the scope of this issue, or should we create separate issue for that?

Thanks.

[1]: https://github.com/privacyidea/privacyidea/pull/3644

**Comment by nilsbehlen** [comment]
Hi, its out of the scope of this issue, so you could create a new one for it. We will of course be implementing it. However, we did not really discuss how we want to handle the information in the applications. So is declined push always equal to cancelled login etc.

**Comment by gryffus** [comment]
I see, thank you for the info!
