### ISSUE TITLE
optionally make OTP input text instead of password

### ISSUE THREAD

**Issue by mat1010** [privacyidea/keycloak-provider#153]
Hello,

the current login form sets the type for the otp field to `type="password"`:
https://github.com/privacyidea/keycloak-provider/blob/986a1764e928f2907654215717421d8075c5d1db/src/main/resources/theme-resources/templates/privacyIDEA.ftl#L173

This causes password managers to not be able to properly differentiate between login and otp fields. The otp login form, shipped by Keycloak, does already correctly set the field to `type="text"`:
https://github.com/keycloak/keycloak/blob/82808e81f2b571100888a4847f54b96d3b70d271/themes/src/main/resources/theme/base/login/login-otp.ftl#L32

Is there a strong reason to explicitly set it to `type="password"`

~ mat1010

**Comment by mat1010** [comment]
I'm using keepassxc as password manager. But the same is true for the integrated MacOS password manager.

It receives the url e.g. `https://auth.example.org` and finds a username + password input field within that site.  I have a username, password and totp key configured for this specific site which causes keepassxc to correctly fill out the login form :heavy_check_mark: 

I'm now being redirected to the otp page. There's, again, a field with type password which resolves again to the password configured for my user, instead of the otp key. 

Since there's no field with type otp, the password managers usually expect a text field for the otp token.

**Comment by nilsbehlen** [comment]
Ok, you probably will have to either make your password manager ignore that field or change it to text locally for your keycloak. Like i said, we cannot change it to text currently.

**Comment by mat1010** [comment]
Ok, that's sad. Would you potentially consider having it configurable in the future?

**Comment by nilsbehlen** [comment]
Yes we can think about it for the next version.

**Comment by mat1010** [comment]
Thanks a lot. I'm looking forward to it.
