### ISSUE TITLE
feature: send static pass

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/keycloak-provider#162]
Add a new setting option called: send static pass, to allow pre-authenticate using a custom pass or empty pass.

**Comment by lukasmatusiewicz** [comment]
@nilsbehlen 
send password -> use keycloak pass? or something like that?

**Comment by nilsbehlen** [comment]
please just a new switch for sendstaticpass.
send password can keep the name, we can double check that the description text states it uses the password of the step before.
there is no "keycloak" password, the password is validated with the user source that is connected to keycloak, so that name would be misleading i think
