### ISSUE TITLE
use KC Settings for language selection / settings

### ISSUE THREAD

**Issue by stefan-kalb** [privacyidea/keycloak-provider#183]
In keycloak you can define which languages are used / available for a realm. Currently the keycloak-provider ignores the setting.

As a user I want a consistent language display for the different screens in a login flow.

1. Please use language settings from keycloak
2. Please use English as fallback
3. Please use either hard coded text in the template or text variables, but not a mix: https://github.com/privacyidea/keycloak-provider/blob/cd3bbaf9ffa895e52f8fa82d78381aae72ed068c/src/main/resources/theme-resources/templates/privacyIDEA.ftl#L43
4. Please don't use a hard coded language switcher just for german: https://github.com/privacyidea/keycloak-provider/blob/cd3bbaf9ffa895e52f8fa82d78381aae72ed068c/src/main/resources/theme-resources/templates/privacyIDEA.ftl#L143
5. Please use the standard "messages_en.properties" for language specific strings

**Comment by lukasmatusiewicz** [comment]
closed by #198
