### ISSUE TITLE
Support TiQR token

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/keycloak-provider#19]
To support the TiQR token we need to be able to display the QR code sent as the challenge.
Otherwise it is simply a challenge response token...

In addition the TiQR token also needs to poll for the result - similar to the Push token.

**Comment by NicoB48** [comment]
Hi, I was about testing Tiqr with keycloak but if my understanding is good, this development has been prioritized as low.

And that may be the reason why I don't see any Qrcode to scan ;-)

Am I wrong ?

**Comment by nilsbehlen** [comment]
Hi,
yes for this provider it is currently not scheduled. If keycloak has another way of doing tiqr, you might try that.
