### ISSUE TITLE
Feature Request:  Workflow enrolle new token linkes back to all registerd tokens 

### ISSUE THREAD

**Issue by isa10110** [privacyidea/keycloak-provider#193]
Hi, I used this app at my company ,  I don't get very deep into that probably its an easy improvement. 
If I enroll an new token, A button near the button enrolls a new token at the end of the dialogue that brings you quickly back to the list of all registered tokens would be more intuitive to me.  

I think it would be more intuitive to me.
a time when I only wanted to register a further backup opportunity fastly this led me into a loop that after that I created 3 of the 2fa keys,  with the same title as I did read very often cause I replaced some keys in the past and the workflow seemed familiar to me.

register multiple tokens at once is probably not the most often workflow, (if you have some keys registered)  for example, if you break or lose a device you would probably register a replacement therefore I would also like the idea of leading me after I've registered a token to lead me back to the list of all registered keys.  

I hope that this ideas are helpful :) 
kind reguards

**Comment by isa10110** [comment]
the butten was called enrolle new token.

**Comment by nilsbehlen** [comment]
Hi, i am not sure i can understand what you are trying to say. This project does not manage token, did you mean to write this in [privacyidea?](https://github.com/privacyidea/privacyidea) or did you use some custom helpdesk interface?

**Comment by isa10110** [comment]
its a frontend to create and deleate tokens for privacy idea if I am wrong I shod probably find that project somewhere diffrent

**Comment by nilsbehlen** [comment]
that is not part of this provider, which is just a plugin for authentication. you will have to bring your idea to the one that created the frontend.
