### ISSUE TITLE
Support U2F

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/keycloak-provider#20]
We need to add the javascript logic to also support challenge response via U2F.

**Comment by wintamute** [comment]
Hi, this is something I'm quite interested in.
Is it just missing the javascript logic part or is there anything that needs to be added/changed in the provider too?
Just trying to get a feeling for what needs to be done, depending on that I might be able to help in this area.

**Comment by jona-samuel** [comment]
Hello
Thank you for your offer to help. I work on this problem and 
I would be happy if you help me with testing and debugging after I finished my first version

**Comment by wintamute** [comment]
Sure.
I'm also trying WebAuthn/FIDO2, would be great if those also work at some point since it's basically an update of U2F.
Just let me know when you're ready.

**Comment by cornelinux** [comment]
We are currently not sure, if we will implement U2F, since we support Webauthn.

**Comment by lukasmatusiewicz** [comment]
Closed via 7d40c512
