### ISSUE TITLE
Cannot cancel from OTP form

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/keycloak-provider#22]
Pressing cancel when prompted to enter the OTP does not cancel.

**Comment by nilsbehlen** [comment]
it can be cancelled if the field has input but not without.

**Comment by cornelinux** [comment]
I think the problem was within keycloak itself. It does not allow sending a form, when no entry is given, so the form can not be sent, to be canceled.

**Comment by nilsbehlen** [comment]
the cancel button could actually be removed since keycloak introduced a button to reset the authentication flow

**Comment by cornelinux** [comment]
Would it make sense to somehow check the version of keycloak, to either show our cancel button or not?

**Comment by cornelinux** [comment]
Keycloak added this functionality itself.
