### ISSUE TITLE
Display PI response message without requiring trigger challenge setting

### ISSUE THREAD

**Issue by crisbailiff** [privacyidea/keycloak-provider#37]
### Scenario

- We would like to use keycloak instead of an existing radius-based web authentication.
- We use only the token PIN + OTP as the two MFA factors for a user
- We do not store any other user password, such as in ldap.

### Setup
I configured the PrivacyIdea keycloak-provider as a new Keycloak authentication flow:
-  "Username Form" REQUIRED
-  "PrivacyIDEA" REQUIRED

In this setup, Keycloak does not ask for or validate any password. The Username form requires only that a valid username is submitted.

### Trigger Challenge behaviour

**"Enable trigger challenge" active:**
- user does not need any keycloak password, only the username is validated
- privacyidea ftl form shows any challenge message or messages if required
- user does not need to provide any token PIN, only the OTP response is required

**In this mode the user does not perform MFA** - there is no check that they know the token PIN.

The '/validate/trigger' API is privileged and skips the PIN check. Once the transaction is started, the unprivileged /validate/check' API does not perform the PIN check in the final step.

**"Enable trigger challenge" inactive:**
- user does not need any keycloak password, only the username is validated
- privacyidea ftl form shows the default prompt "Please enter the OTP"
- user can successfully authenticate with token PIN + OTP (e.g. TOTP)
- user can obtain a challenge (e.g. SMS) using a challenge token PIN
- message shown for a challenge token PIN doesn't change - remains as "Please enter the OTP" (along with an "Authentication failed" banner)
- user can successfully authenticate with a challenge OTP (e.g. from the SMS) but only by re-entering the challenge token PIN and the OTP
- entering OTP alone fails

**In this mode the user does perform MFA** - they require a PIN + OTP, however this mode has some usability problems for us:

- users do not get any feedback message that a challenge worked (e.g. an SMS has been sent)
- at the second step, users must re-enter the same PIN along with their OTP but there is no visible difference between this step and the first

### Expected Outcome

Users who have only a token PIN + OTP should be able to authenticate via MFA without confusion:
- if a user uses a challenge token, the PrivacyIdea challenge message should be displayed
- entering the challenge should not require re-entering the PIN

I would like to make the user experience as similar as possible to our existing RADIUS behaviour (which relies on /validate/check throughout), so that we do not need to issue new passwords for every user or store those passwords outside of PrivacyIdea.

Looking at the provider code, it seems the basic requirement is:
- pass the "message" from the /validate/check response back to the template to be shown to the user
- retain the "transaction_id" from the response (if provided) and re-supply this on the subsequent call to /validate/check

This seems to be mostly in place for the /validate/triggerchallenge path, but skipped for the /validate/check path.

I have attached a diff for my attempt at implementing this enhancement. I did not provide a PR as I don't wish to suggest this is merge-ready code (my java skills are basic) but this "works for me" and hopefully will be a prompt for you to consider support for this scenario.

### Other Considerations
- It would be nice for the template to be able to identify the challenge response state and suppress the "Authentication Failed" banner
- In my change, I passed the PI message back to the form via a session AuthNote. I'm not sure how the keycloak authenticator state is otherwise persisted between invocations. The transaction_id seems to be currently stored only in a class variable, but I can see an unused Const declaration suggesting you might store it as an AuthNote also? Is a transaction going to survive across server/jar reloads or in a clustered Keycloak deployment?
- There is no assumption of a single challenge required - if they transaction_id is set, it is passed forwards. This would support the logic in https://github.com/privacyidea/privacyidea/issues/2163#issue-603286079 etc. (which is how RADIUS challenge has always worked)

[PrivacyIDEAAuthenticator-otpchallenge.diff.txt](https://github.com/privacyidea/keycloak-provider/files/4608319/PrivacyIDEAAuthenticator-otpchallenge.diff.txt)

**Comment by crisbailiff** [comment]
Missed the Const.java change. Updated diff attached.

[PrivacyIDEAAuthenticator-otpchallenge.diff-2.txt](https://github.com/privacyidea/keycloak-provider/files/4608443/PrivacyIDEAAuthenticator-otpchallenge.diff-2.txt)

**Comment by nilsbehlen** [comment]
Hi,
thanks for your feedback. Currently, authenticating with challenge-response is only possible via a service account. If a challenge is triggered via /validate/check, the plugin does not recognize it and instead treats it as a failed authentication. In the next version of the plugin, both ways of challenge-response will be supported. The design of the plugin *should* then support mutliple chained challenge-responses naturally, but we will have to test that when the time comes.

Regarding the lifetime of the transaction_id: It persists as long as the authenticator object is kept alive by the server. If the jar is reloaded, it would be garbage-collected, but i do not really see how the jar would be reloaded while logging in? In the earlier version, it was stored in the AuthNote, which means it is passed to the ftl and then, upon submitting, back to the authenticator. This is obviously not necessary as the authenticator object is kept alive for the login process and its member variables are always accessible.
