### ISSUE TITLE
User not always correctly resolved

### ISSUE THREAD

**Issue by ludimax** [privacyidea/keycloak-provider#40]
I'm trying to implement integration of Privacyidea 3.3.1 with Keycloak 10.0.1 by using this keycloak-provider. User matching does not always goes well, resulting in users doing multiple login attempts. In Privacyidea logs shows validation attempt of user1, we see that it matches user2 first:

1103 | 2020-06-03 12:30:19 | POST /validate/check | 1 |   | serial |   |   | user1 | realm | sso-ldap |   | ip | Found matching challenge | OK | OK |   |   | server
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1102 | 2020-06-03 12:30:18 | POST /validate/check | 0 |   | serial | totp |   | user2 | realm | sso-ldap |   | ip | wrong otp value

I've checked the validate endpoint on the PI side, this one is always ok and consistent, so problem should be in Keycloak / Keycloak provider.

Setup:
- Privacyidea 3.3.1
- Keycloak 10.0.1 (also in 9.0.3)
- Keycloak-provider built from master branch (issue is with release as well). 
- Both Keycloak & PI uses LDAP from Active Directory

**Comment by ludimax** [comment]
Sometimes even stranger with a mixup of a  third user:

1233 | 2020-06-03 12:57:48 | POST /validate/check | 1 |   | serial |   |   | user1 | realm | sso-ldap |   | ip | Found matching challenge | OK | OK |   |   | server
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1232 | 2020-06-03 12:57:44 | POST /validate/check | 0 |   | serial | totp |   | user3 | realm | sso-ldap |   | ip | wrong otp value | OK | OK |   |   | server
1231 | 2020-06-03 12:57:36 | GET /token/ | 1 |   |   |   | admin | user1 | realm | sso-ldap |   | ip | realm: None | OK | OK |   |   | server
1230 | 2020-06-03 12:57:36 | POST /validate/triggerchallenge | 1 |   | serial |   |   | user1 | realm | sso-ldap |   | ip | triggered 1 challenges | OK

**Comment by cornelinux** [comment]
We do not understand what you mean with "usermatching"?
Usually the plugin should not mangle the user.
It should send the user, that actually tries to login.
Or - you missed some information for us to understand.

**Comment by ludimax** [comment]
I know, usermatching is probably not correct. Basically it's fairly simple (as far as I know), Keycloak-provider gets userdata from Keycloak (username etc), combined with the input from the otp form, and the keycloak PI provider queries PI validate endpoint to check this. Somehow, not always is the correct _currentUserName being used to query the validation endpoint.

**Comment by nilsbehlen** [comment]
Hi,
that seems to be the problem - the member variables are overwritten if somebody else attempts to login while another login is still going on.
It will be fixed soon.
