### ISSUE TITLE
Issue with Enrollment

### ISSUE THREAD

**Issue by mattronix** [privacyidea/keycloak-provider#42]
Hello Team,

Currently using OTP works fine if the user has a token but if the user does not have a token assigned in PrivacyIDEA yet the enter OTP screen still shows and you don't get prompted to enroll a token.

Also, the cancel button does not work unless you enter text, think that's a bug?

For the rest amazing work loving the fact that I can finally do push/sms auth in keycloak.

**Comment by nilsbehlen** [comment]
Hi,

did you activate token enrollment in the config of the plugin? It works for me on Keycloak 10.0.1.

The cancel button is not that great, we will have to look at it again or maybe remove it, as you can reset the authentication by clicking the the button next to the username on top.

**Comment by ludimax** [comment]
Have the same issue as well. Token enrollment in v0.5 doesn't work anymore

**Comment by nilsbehlen** [comment]
Which version of keycloak are you using? What does the log say?

**Comment by ludimax** [comment]
I'm using Keycloak 10.0.2, from the Keycloak logs:
[0m[31m08:06:41,694 ERROR [stderr] (default task-8) javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
2020-06-10T10:06:41.694+02:00 | [0m[31m08:06:41,694 ERROR [stderr] (default task-8) at org.glassfish.jakarta.json@1.1.6//org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:577)
-- | --
  | 2020-06-10T10:06:41.695+02:00 | [0m[31m08:06:41,694 ERROR [stderr] (default task-8) at org.glassfish.jakarta.json@1.1.6//org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:394)
  | 2020-06-10T10:06:41.695+02:00 | [0m[31m08:06:41,695 ERROR [stderr] (default task-8) at org.glassfish.jakarta.json@1.1.6//org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:402)
  | 2020-06-10T10:06:41.695+02:00 | [0m[31m08:06:41,695 ERROR [stderr] (default task-8) at org.glassfish.jakarta.json@1.1.6//org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
  | 2020-06-10T10:06:41.695+02:00 | [0m[31m08:06:41,695 ERROR [stderr] (default task-8) at org.glassfish.jakarta.json@1.1.6//org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:87)
  | 2020-06-10T10:06:41.696+02:00 | [0m[31m08:06:41,695 ERROR [stderr] (default task-8) at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.authenticator.Endpoint.sendRequest(Endpoint.java:117)
  | 2020-06-10T10:06:41.696+02:00 | [0m[31m08:06:41,696 ERROR [stderr] (default task-8) at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.authenticator.PrivacyIDEAAuthenticator.authenticate(PrivacyIDEAAuthenticator.java:131)
  | 2020-06-10T10:06:41.696+02:00 | [0m[31m08:06:41,696 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:438)
  | 2020-06-10T10:06:41.696+02:00 | [0m[31m08:06:41,696 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:247)
  | 2020-06-10T10:06:41.697+02:00 | [0m[31m08:06:41,697 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:381)
  | 2020-06-10T10:06:41.697+02:00 | [0m[31m08:06:41,697 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:180)
  | 2020-06-10T10:06:41.697+02:00 | [0m[31m08:06:41,697 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:158)
  | 2020-06-10T10:06:41.698+02:00 | [0m[31m08:06:41,698 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:936)
  | 2020-06-10T10:06:41.698+02:00 | [0m[31m08:06:41,698 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:311)
  | 2020-06-10T10:06:41.698+02:00 | [0m[31m08:06:41,698 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:282)
  | 2020-06-10T10:06:41.699+02:00 | [0m[31m08:06:41,699 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:266)
  | 2020-06-10T10:06:41.699+02:00 | [0m[31m08:06:41,699 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:339)
  | 2020-06-10T10:06:41.699+02:00 | [0m[31m08:06:41,699 ERROR [stderr] (default task-8) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2020-06-10T10:06:41.700+02:00 | [0m[31m08:06:41,699 ERROR [stderr] (default task-8) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | 2020-06-10T10:06:41.700+02:00 | [0m[31m08:06:41,700 ERROR [stderr] (default task-8) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2020-06-10T10:06:41.700+02:00 | [0m[31m08:06:41,700 ERROR [stderr] (default task-8) at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  | 2020-06-10T10:06:41.701+02:00 | [0m[31m08:06:41,700 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
  | 2020-06-10T10:06:41.701+02:00 | [0m[31m08:06:41,701 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:535)
  | 2020-06-10T10:06:41.701+02:00 | [0m[31m08:06:41,701 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:424)
  | 2020-06-10T10:06:41.701+02:00 | [0m[31m08:06:41,701 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:385)
  | 2020-06-10T10:06:41.702+02:00 | [0m[31m08:06:41,702 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
  | 2020-06-10T10:06:41.702+02:00 | [0m[31m08:06:41,702 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:387)
  | 2020-06-10T10:06:41.702+02:00 | [0m[31m08:06:41,702 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
  | 2020-06-10T10:06:41.703+02:00 | [0m[31m08:06:41,703 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
  | 2020-06-10T10:06:41.703+02:00 | [0m[31m08:06:41,703 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
  | 2020-06-10T10:06:41.703+02:00 | [0m[31m08:06:41,703 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
  | 2020-06-10T10:06:41.704+02:00 | [0m[31m08:06:41,704 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
  | 2020-06-10T10:06:41.704+02:00 | [0m[31m08:06:41,704 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
  | 2020-06-10T10:06:41.704+02:00 | [0m[31m08:06:41,704 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
  | 2020-06-10T10:06:41.705+02:00 | [0m[31m08:06:41,704 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
  | 2020-06-10T10:06:41.705+02:00 | [0m[31m08:06:41,705 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
  | 2020-06-10T10:06:41.705+02:00 | [0m[31m08:06:41,705 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
  | 2020-06-10T10:06:41.705+02:00 | [0m[31m08:06:41,705 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | 2020-06-10T10:06:41.706+02:00 | [0m[31m08:06:41,706 ERROR [stderr] (default task-8) at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
  | 2020-06-10T10:06:41.706+02:00 | [0m[31m08:06:41,706 ERROR [stderr] (default task-8) at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
  | 2020-06-10T10:06:41.706+02:00 | [0m[31m08:06:41,706 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
  | 2020-06-10T10:06:41.707+02:00 | [0m[31m08:06:41,707 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
  | 2020-06-10T10:06:41.707+02:00 | [0m[31m08:06:41,707 ERROR [stderr] (default task-8) at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:91)
  | 2020-06-10T10:06:41.707+02:00 | [0m[31m08:06:41,707 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | 2020-06-10T10:06:41.708+02:00 | [0m[31m08:06:41,707 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | 2020-06-10T10:06:41.708+02:00 | [0m[31m08:06:41,708 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
  | 2020-06-10T10:06:41.708+02:00 | [0m[31m08:06:41,708 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | 2020-06-10T10:06:41.708+02:00 | [0m[31m08:06:41,708 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
  | 2020-06-10T10:06:41.709+02:00 | [0m[31m08:06:41,709 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | 2020-06-10T10:06:41.709+02:00 | [0m[31m08:06:41,709 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  | 2020-06-10T10:06:41.709+02:00 | [0m[31m08:06:41,709 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | 2020-06-10T10:06:41.710+02:00 | [0m[31m08:06:41,710 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
  | 2020-06-10T10:06:41.710+02:00 | [0m[31m08:06:41,710 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
  | 2020-06-10T10:06:41.710+02:00 | [0m[31m08:06:41,710 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | 2020-06-10T10:06:41.710+02:00 | [0m[31m08:06:41,710 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | 2020-06-10T10:06:41.711+02:00 | [0m[31m08:06:41,711 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | 2020-06-10T10:06:41.711+02:00 | [0m[31m08:06:41,711 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | 2020-06-10T10:06:41.711+02:00 | [0m[31m08:06:41,711 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | 2020-06-10T10:06:41.712+02:00 | [0m[31m08:06:41,712 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | 2020-06-10T10:06:41.712+02:00 | [0m[31m08:06:41,712 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
  | 2020-06-10T10:06:41.712+02:00 | [0m[31m08:06:41,712 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | 2020-06-10T10:06:41.713+02:00 | [0m[31m08:06:41,713 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | 2020-06-10T10:06:41.713+02:00 | [0m[31m08:06:41,713 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  | 2020-06-10T10:06:41.713+02:00 | [0m[31m08:06:41,713 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | 2020-06-10T10:06:41.714+02:00 | [0m[31m08:06:41,713 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
  | 2020-06-10T10:06:41.714+02:00 | [0m[31m08:06:41,714 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | 2020-06-10T10:06:41.714+02:00 | [0m[31m08:06:41,714 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
  | 2020-06-10T10:06:41.714+02:00 | [0m[31m08:06:41,714 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
  | 2020-06-10T10:06:41.715+02:00 | [0m[31m08:06:41,715 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
  | 2020-06-10T10:06:41.715+02:00 | [0m[31m08:06:41,715 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
  | 2020-06-10T10:06:41.715+02:00 | [0m[31m08:06:41,715 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | 2020-06-10T10:06:41.716+02:00 | [0m[31m08:06:41,715 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | 2020-06-10T10:06:41.716+02:00 | [0m[31m08:06:41,716 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
  | 2020-06-10T10:06:41.716+02:00 | [0m[31m08:06:41,716 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
  | 2020-06-10T10:06:41.716+02:00 | [0m[31m08:06:41,716 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
  | 2020-06-10T10:06:41.717+02:00 | [0m[31m08:06:41,717 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
  | 2020-06-10T10:06:41.722+02:00 | [0m[31m08:06:41,722 ERROR [stderr] (default task-8) at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
  | 2020-06-10T10:06:41.722+02:00 | [0m[31m08:06:41,722 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
  | 2020-06-10T10:06:41.723+02:00 | [0m[31m08:06:41,722 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
  | 2020-06-10T10:06:41.723+02:00 | [0m[31m08:06:41,723 ERROR [stderr] (default task-8) at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
  | 2020-06-10T10:06:41.723+02:00 | [0m[31m08:06:41,723 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
  | 2020-06-10T10:06:41.723+02:00 | [0m[31m08:06:41,723 ERROR [stderr] (default task-8) at io.undertow.core@2.1.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
  | 2020-06-10T10:06:41.724+02:00 | [0m[31m08:06:41,724 ERROR [stderr] (default task-8) at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
  | 2020-06-10T10:06:41.724+02:00 | [0m[31m08:06:41,724 ERROR [stderr] (default task-8) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
  | 2020-06-10T10:06:41.724+02:00 | [0m[31m08:06:41,724 ERROR [stderr] (default task-8) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
  | 2020-06-10T10:06:41.725+02:00 | [0m[31m08:06:41,725 ERROR [stderr] (default task-8) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
  | 2020-06-10T10:06:41.725+02:00 | [0m[31m08:06:41,725 ERROR [stderr] (default task-8) at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ludimax** [comment]
Maybe something to do with
`static final String ENDPOINT_TOKEN = "/token";`
Does it needs to be changed to /token/? /token is now a 308 redirect.

**Comment by nilsbehlen** [comment]
Yes it definitely needs to be changed, i thought it was included in the last PR, my bad.
