### ISSUE TITLE
Rename input field #pi_otp to #otp 

### ISSUE THREAD

**Issue by mattronix** [privacyidea/keycloak-provider#43]
Hello Team,

This is more of a feature request but equally, take it lightly since it's not really a feature of privacyIDEA directly so here we go: 

With our keycloak we use something called SAML2AWS (https://github.com/Versent/saml2aws) This allows us to authenticate to AWS using SAML, currently, it supports the standard TOTP form from keycloak but tested with this provider and does not. 

I am guessing its due to a form field name maybe or form controls, I'm not sure if you want to support it but if you do this would-be killer as we could do our AWS role assignment with 2FA from Keycloak and use Privacy idea for the whole process, we currently use privacyIDEA with Fortinet + freeradius and want to integrate it with keycloak.

Amazing work so on privacyIDEA!

**Comment by mattronix** [comment]
Would this be possible?

**Comment by mattronix** [comment]
I did some digging into the code of saml2aws and it seems to look for fields called otp or totp. 

Can we rename pi_otp to otp?

func containsTotpForm(doc *goquery.Document) bool {
	// search totp field at Keycloak < 8.0.1
	totpIndex := doc.Find("input#totp").Index()

	if totpIndex != -1 {
		return true
	}

	// search otp field at Keycloak >= 8.0.1
	totpIndex = doc.Find("input#otp").Index()

	if totpIndex != -1 {
		return true
	}

	return false
}

**Comment by nilsbehlen** [comment]
Hey,
can you do it yourself and check if it works for you, then do a pull request? Since i do not have your setup i can just check if everything else works.
The input should be this
https://github.com/privacyidea/keycloak-provider/blob/9169acb47567a015af6eb521c8da8d41dda18e93/src/main/resources/theme-resources/templates/privacyIDEA.ftl#L23
and its occurences above.
Thank you

**Comment by mattronix** [comment]
Sure, did some basic testing so far and not quite got it, the rename works but for some reason then the form post returns a 400 error.

Any ideas or direction you can point me in?

**Comment by nilsbehlen** [comment]
Hi, can you open a draft pull request so i can check it out?
From the top of my head i don't know why it would return a 400.

**Comment by mattronix** [comment]
Sure will do in the morning :)

**Comment by mattronix** [comment]
sorry for slow reply not had time to test yet will be following 1/2 weeks.

**Comment by mattronix** [comment]
made the PR on the weekend :)

**Comment by nilsbehlen** [comment]
this will be included in v0.6. and is already merged to master.
