### ISSUE TITLE
Token is created without validating OTP code (Difference in enrollment procedure vs keycloak)

### ISSUE THREAD

**Issue by mzaranbnl** [privacyidea/keycloak-provider#51]
Tested using
Keycloak 7.0.0 with privacyidea 3.3 & provider v0.5
Keycloak 9 & 10.0.2 with privacyidea 3.4 & provider v0.5

Not sure if this was a design choice for privacyidea or just something unique to keycloak and not noticed when developing the keycloak-provider.

This is just a rough observation of what I noticed during testing. The overview pretty much describes the TOTP creation of keycloak vs that of privacyidea.

**Default keycloak**
_This is helpful for users who are caught off guard and want to come back to enroll._
- During initial OTP enrollment the "Mobile Authenticator Setup" doesn't actually create the token in keycloak till you validate the OTP.  At the same time if a user just closes the browser no token is actually created or linked to that users account. 

**Keycloak with privacyidea provider**
- During intial OTP enrollment keycloak / privacyidea creates the token before you validate the OTP code in the keycloak form. We even tried to enter 1 character in the OTP field of the form and hit cancel. We assumed this would delete / invalidate the token that wasn't confirmed. The token was created once the user logged in and did not require passing validation like the default keycloak enrollment requires.

**Other differences we noticed related to OTP enrollment**
_Keycloak has an "unable to scan" option that allows you to manually enter a code. Is this possible in the privacyidea form?_

_The other odd behavior we noticed in keycloak. If you type the wrong OTP code in keycloak during initial OTP creation the QR code changes without any notification reporting it (This part seems like a poor design for initial setup). The fact privacyidea doesn't change the QR code during initial setup is helpful in that aspect._

**Comment by nilsbehlen** [comment]
Hi, your observations are correct and that is how privacyidea is meant to work. It *might* be possible for the plugin to delete the token if it was not confirmed, but that also depends on the configuration of privacyidea. We are also not quite sure if we want to support token enrollment by plugins so this "feature" is kind of experimental. However, the "unable to scan" option is something we can add in the [future](https://github.com/privacyidea/keycloak-provider/issues/52).

**Comment by mzaranbnl** [comment]
Thank you for confirming the functionality and considering the "unable to scan" option in a future release.
