### ISSUE TITLE
SMS and Push cant choose

### ISSUE THREAD

**Issue by mattronix** [privacyidea/keycloak-provider#55]
Currently, when we login we get both a push and an SMS message this is quite expensive considering we use push as a primary, is it possible to have a drop-down selection so the user can choose between the Methods they have configured like:

- Webauthn
- Push
- SMS
- TOTP

Thanks :)

**Comment by nilsbehlen** [comment]
This might be an interesting feature. We will discuss if this should be included in the next version.

**Comment by cornelinux** [comment]
This is not the usual behaviour like privacyIDEA is intended to work.
This of course could be implemented, but that puts more logic into a plugin than we usually want.

**Comment by lukasmatusiewicz** [comment]
A proper feature is added in the privacyIDEA v.3.8

You can use it by adding this policy: authentication -> miscellaneous -> preferred_client_mode.

Keycloak implementation of the `preferred_client_mode`: #121
