### ISSUE TITLE
Not able to get OTP via email using keycloak

### ISSUE THREAD

**Issue by avdevs** [privacyidea/keycloak-provider#56]
I have setup keycloak 4.8 and privacyidea provider but not able to get OTP via email.
I am able to get token and assigned user to the token at privacyidea dashboard. 
here is the screenshot of token 
![image](https://user-images.githubusercontent.com/16224777/105132289-b0475000-5b10-11eb-917e-00dd9bc38364.png)

I have also made the setting for EMail Token settings and SMTP server configuration. Also able to get testing email using privacy idea.
![image](https://user-images.githubusercontent.com/16224777/105130736-96583e00-5b0d-11eb-85c1-613c2342bc04.png)

Here is the configuration of keycloak side 
![image](https://user-images.githubusercontent.com/16224777/105130872-d0294480-5b0d-11eb-9fd3-4c938894903d.png)

![image](https://user-images.githubusercontent.com/16224777/105130823-ba1b8400-5b0d-11eb-8252-fff70fb4311f.png)

Is there something i have missed or it is the issue of privacyidea provider?

**Comment by nilsbehlen** [comment]
Hi, 
i think the URL should be https. If that does not help, you might want to enable logging and check the keycloak log.

**Comment by avdevs** [comment]
> Hi,
> i think the URL should be https. If that does not help, you might want to enable logging and check the keycloak log.

I think URL is not a problem because if you see the steps here, they use the same localhost URL  https://community.privacyidea.org/t/how-to-use-keycloak-with-privacyidea/1132

**Comment by nilsbehlen** [comment]
Then enable logging and check what the log says please.

**Comment by avdevs** [comment]
> Then enable logging and check what the log says please.

there is nothing with the keycloak log file.

keyclaok showing me authenticator screen After i login with the username and password instead of sending me an email with OTP. 
![image](https://user-images.githubusercontent.com/16224777/105177391-9fb4cb00-5b4c-11eb-97d8-5d41a010653e.png)
