### ISSUE TITLE
TransactionID should be sent to /validate/check for all token challenges

### ISSUE THREAD

**Issue by crisbailiff** [privacyidea/keycloak-provider#58]
The transactionID should be returned to the /validate/check endpoint in the response to every challenge request, not just the calls for the push token.

This allows support for SMS, Email and other challenge tokens which are triggered by the user providing the appropriate token PIN.

This is the same as the request in #37 where I provided some sample code. Although that is marked resolved, v0.5.1 does not send the transactionID with the response during an OTP challenge (e.g. SMS) - the user must re-enter the token PIN as well as the OTP.

(Not clear if this fix was lost in the migration to java-sdk - I didn't test v0.5 or lower).

I found that adding the transactionID to the validateCheck call appears sufficient - tokens are now working as expected for each of the types, including when a user has multiple tokens and selects between them with different PINs.

I can create a PR if you think this is the appropriate fix:

```java
--- a/src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
+++ b/src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
@@ -198,7 +198,7 @@ public class PrivacyIDEAAuthenticator implements org.keycloak.authentication.Aut
             }
         } else {
             String otp = formData.getFirst(Const.FORM_PI_OTP);
-            PIResponse response = privacyIDEA.validateCheck(currentUserName, otp);
+            PIResponse response = privacyIDEA.validateCheck(currentUserName, otp, transactionID);
 
             if (response != null) {
                 // A challenge was triggered, display its message and pass the transaction id

```

**Comment by nilsbehlen** [comment]
Hi, thanks for bringing this to attention. I guess it was lost in the transition to the sdk.
This will be fixed in the next release, which will support multiple challenge-response successively.

**Comment by cornelinux** [comment]
This is also contained in the PR #53
