### ISSUE TITLE
Installation/configuration question -- Keycloak.X 

### ISSUE THREAD

**Issue by skug67** [privacyidea/keycloak-provider#61]
With the newer (less resource intensive) Keycloak.X the base theme is no longer present in the filesystem for you to just drop in privacyIDEA.ftl

Does anyone know how you could install this provider in a Keycloak.X environment?

**Comment by nilsbehlen** [comment]
Hi, this provider currently does not work with keycloakx. While you can just deploy the jar to kcx (into the provider folder, see the readme there), some dependencies are not resolved properly so it does not work yet.

**Comment by skug67** [comment]
I got a little adventurous, extracted the base theme from the embedded jar (lib/lib/main/org.keycloak.keycloak-themes-12.0.4.jar) dropped in the privacyIDEA.ftl file into base/login and then recompressed (just the base theme) and put the resulting jar into the provider folder.  Somewhat to my surprise, it seems to work.  Obviously, a bit of a hassle (especially if future releases of keycloakx muck around with the base theme....). The keycloak documentation suggests there's some way to extend a theme w/o duplicating all the items you don't want to change.  But I haven't been able to figure out how to do that..... (I have zero actual coding knowledge, just a trial-and-error guy willing to experiment with whatever I glean from google/forums/etc).

**Comment by skug67** [comment]
Yup, as noted above I did it by

(1) Extracting the base theme packaged in keycloakx (from lib/lib/main/org.keycloak.keycloak-themes-12.0.4.jar for the current release)
(2) Copying privacyIDEA.ftl into the base/login directory created in step (1).
(3) Recompressing the entire theme into a new jar file (I called it keycloak-base-theme-with-pi.jar) and placing that file into the providers directory for the keycloakx installation.

[I had previously just created as base/login directory under the themes directory of the keycloakx installation and copied privacyIDEA.ftl into there and it didn't work.  I haven't deleted that, so it's barely possible that _both_ the new jar in providers and the ftl under themes are necessary.  But I strongly suspect it's just the jar]

The documentation suggests that there is some way to simply "extend" the base theme rather than extracting/re-compressing the whole thing.  Which would be good.  Because as I'm doing it, I'll lose any changes that Keycloak makes to the base theme unless I go through extracting/re-compressing for every upgrade cycle.  But I haven't figured that out.....

**Comment by nilsbehlen** [comment]
Thanks for sharing your findings. Which version of this plugin did you use? 
I had tried with the current master branch when you openend this issue and didn't get it to work. But my issue was not related to the theme.

**Comment by skug67** [comment]
Used the pre-packaged jar from v0.5.1

**Comment by skug67** [comment]
I can confirm (I guess that's the right word) that this does not work when using the pre-packaged jar from v0.6 webauthn.

**Comment by skug67** [comment]
There's no particular reason it took me a week to go look for this, but the error thrown when trying to login with the 0.6 pre-packaged jar is

> ERROR [org.key.ser.err.KeycloakErrorHandler] (vert.x-worker-thread-5) Uncaught server error: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

No idea if that's helpful or not.

**Comment by nilsbehlen** [comment]
Hey, thanks for the info. 
The problem stems from the okhttp3 dependency that is introduced with 0.6 and is implemented in kotlin.
Since keycloakx is still in preview phase, we are currently not working on this problem, but in the future we will for sure.

**Comment by JohannesKreuzer** [comment]
@nilsbehlen any updates on the support for Quarkus based keycloak server? With the last release the Quarkus distribution got default.

**Comment by nilsbehlen** [comment]
thanks for pointing this out. I will start working on it soon.

**Comment by nilsbehlen** [comment]
https://github.com/privacyidea/keycloak-provider/issues/89

**Comment by arozmarin** [comment]
Hi guys, sorry to ask a question but I tried privacyidea plugin on keycloack 17 and can't get it work. I copy plugin int different folders and no success. I tried in /lib/lib/main, lib/lib/deployment. Into which folder should I copy plugin to make it work? 
thanks in advance and sorry to be annoying. 
Oh yeah and which version to use latest or any older version?
