### ISSUE TITLE
How to compile the project as JAR

### ISSUE THREAD

**Issue by datenzar** [privacyidea/keycloak-provider#62]
Hi there,

we're in the progress of troubleshooting a bug with this plugin and therefore want to compile the current master branch.

The first challenge to link the privacy-sdk I could solve by adjusting the pom.xml and link it to the github repository directly. Now I can create the JAR with docker using 
```
docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven mvn clean install
```
but after loading the JAR into Keycloak I get a `NoClassDefFoundError` for the IPILog interface (I guess it's missing in the manifest) and I'm feeling kind of lost here. 

Can please someone point me on how to get this project compiled properly?

Thx!

**Comment by nilsbehlen** [comment]
Hello, what are the contents of the JAR? 
Usually you want to build the sdk first then the provider. The contents of the sdk should be contained in the final jar using the shade plugin.

**Comment by datenzar** [comment]
Hi @nilsbehlen,
thanks for the response! In the meantime a colleague was now able to compile without using Docker but the plain vanilla installation of maven on the machine. So it seems there's an incompatibility in the way, the maven-container builds are expected to be executed.

**Comment by nilsbehlen** [comment]
Good to hear. If you find a bug you can just open a new issue. I will close this one for now.
