### ISSUE TITLE
Admin password encoding - related to #67

### ISSUE THREAD

**Issue by SorinMiron** [privacyidea/keycloak-provider#68]
Related to #67 

I have been struggled with the issue from above. When I changed the configuration to not use emails, the problem still appears. 
After I changed the admin password from privacyIDEA Auth config, the system are working fine. The old password contained special characters and the new one contains only letters. I tested this scenario with 3 type of tokens:
push - it's not working;
totp/hotp - it's ok.

I'm thinking that the admin password is **encoded** before it is sent to privacyIDEA.

**Comment by nilsbehlen** [comment]
this is the same as #67 so ill close this for now.
