### ISSUE TITLE
TOTP token with pin only works with keycloak if the pin is omitted

### ISSUE THREAD

**Issue by rtheys** [privacyidea/keycloak-provider#70]
Hi,

I'm using privacyidea 3.6 with keycloak. I've configured a TOTP token with a PIN.

In the privacyidea admin interface, I locate the token and use the "test token" feature. If I enter the PIN followed by the OTP from my phone and press "test token" it works. If I omit the PIN "test token" fails and "test otp only" works (as expected). So I assume the PIN is correctly set.

When I trigger an authentication with keycloak and keycloak asks me for my OTP, I have to enter the OTP _without_ the PIN, otherwise validation of the OTP fails.

Is this by design? Does it not defeat the purpose of setting a pin?

Regards,
Rik

**Comment by nilsbehlen** [comment]
Hi,
what is the configuration of the plugin?
Can you activate debug logging in the plugin and post it?

**Comment by rtheys** [comment]
Hi,

The configuration of the plugin in keycloak:

Realm: my user realm
Enable sending password: off
enable trigger challenge: on
service account: trigger-admin
service account password: secret
enable token enrollment: off
enrollment token type: totp
enable logging: on

How can I enable debug logging in the plugin?

Regards,
Rik

**Comment by nilsbehlen** [comment]
You already have it enabled. Check the logfile in the keycloak folder.
Moreover, you have triggerchallenge enabled which might result in getting a transaction id which is then sent with your PIN+OTP (check logs for that). This will prevent it from working because PIN+OTP is not challenge-response.
You can try disabling triggerchallenge and try again.

**Comment by rtheys** [comment]
Hi,

In the keycloak logs, I only see the response from privacyidea, but not the request?

If I disable the triggerchallenge it works, but then I lose the ability to authenticate with my webauthn token instead of the otp.

Regards,
Rik

```
2021-07-08 09:08:41,868 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (OkHttp https://my.server.here/...) /validate/check:
{
  "detail": {
    "message": "Response did not match for 2 tokens.",
    "threadid": 140451122140928
  },
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "status": true,
    "value": false
  },
  "time": 1625728121.8457553,
  "version": "privacyIDEA 3.6",
  "versionnumber": "3.6",
  "signature": "rsa_sha256_pss:63f7ba8ddbd9fe4ff3987c702e3b6f89a1b8af382de74fac77f936c62a5629a20454c6c8c9420fa47fc28b6ac30a543bdf0bb3f25a59a1283a7cece7cfc8a6e55c5eca2790b472bc6ce81427051aeffaa1ab24f7c7530e09f8518178c17c843586a3f183c91189c31749a6f6853debdb67bd1c8e0b771f23cf1047a09a88b2e32ff2f87c225b8cddd0623c4844c4f65586ab4d8a51b5fdc03c432c6f528ddd95c513b43afd3088b4c871059393e536ad6d6701d68b9fd734c62500de9988779e2d1b5a70a1a4215d9bc63e2145771561ccd84261d450401a632bf160ea4cd5798ee07593b219f35bfb5e9659b33de7b89734c89038c11440901f59f04d30a6a9"
}
```

**Comment by nilsbehlen** [comment]
Yes, this is the problem you are having: One token is challenge-response and the other one isn't. The plugin will always send the transactionid if there is one (which is always in your case).
You can change the mode of your OTP token to challenge-response by creating a policy:
scope: authentication, category: misc, name: challenge_response
there you can enter the types of token which should be used in challenge-response mode.
This should make it work.

**Comment by rtheys** [comment]
Hi,

Your suggestion with the policy does not work. I will ask in the community section if this is possible.

Regards,
Rik
