### ISSUE TITLE
[Question] privacyIDEA.ftl installation v0.6.1

### ISSUE THREAD

**Issue by SherifNagy** [privacyidea/keycloak-provider#73]
In the Readme, it mention that privacyIDEA.ftl file is being installed automatically while deploying the jar into wildfly , however, seems like I can't find the file in the /theme/base/login/ how is the file is getting installed?

As far as I understand, this file is needed to "enrol / show QRcode " when keycloak provider is configured to enrol token if it doesn't exists, is that correct?

In latest release, the file is not attached, however in version 0.6.0 it was attached with the release tag

**Comment by nilsbehlen** [comment]
Hi,
the jar will not be unpacked by keycloak. Instead, it is deployed to /standalone/content/.../.../content

**Comment by SherifNagy** [comment]
Thanks! I reverted back to 0.5.1 and everything works, I guess I hit a bug, I will open another issue
