### ISSUE TITLE
Keycloak 15 support - freemarker template privacyIDEA.ftl not compatible

### ISSUE THREAD

**Issue by ludimax** [privacyidea/keycloak-provider#80]
Current freemarker template is not compatible with Keycloak 15.
Error logging:

Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> tokenType  [in template "privacyIDEA.ftl" at line 11, column 26]

FTL stack trace ("~" means nesting-related):
	- Failed at: #if tokenType = "push"  [in template "privacyIDEA.ftl" at line 11, column 21]
	~ Reached through: #nested "form"  [in template "template.ftl" in macro "registrationLayout" at line 126, column 11]
	~ Reached through: @layout.registrationLayout; section  [in template "privacyIDEA.ftl" at line 2, column 1]

**Comment by nilsbehlen** [comment]
Hi, have you been able to resolve the problem?
