### ISSUE TITLE
Username encoding return Invalid User and One Time Password is not sent to User email

### ISSUE THREAD

**Issue by Samnang-An** [privacyidea/keycloak-provider#85]
Hi,

I just upgrade the adapter from 0.5.1 to 0.6.1 and I got this error after login in successfully
> {
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "error": {
      "code": 905,
      "message": "ERR905: Invalid user."
    },
    "status": false
  }

From accesslog in PrivacyIdea server, I found out the username is encoded in 0.6.1 but not in 0.5.1

- 0.6.1
> Entering get_user_from_param with arguments ({'realm': 'abc', 'user': 'abc%40test.com'},) and keywords {}
- 0.5.1 
> Entering get_user_from_param with arguments ({'user': 'abc@test.com', 'realm': 'abc'},) and keywords {}

From this error, the email is not sent to the user for the code to log in.

Best Regards,
Samnang

**Comment by nilsbehlen** [comment]
Hi, which version of the server are you using?

**Comment by Samnang-An** [comment]
Hi nilsbehlen,

Sorry for the late reply.
I am using privacyIDEA 3.5.2 and Keycloak 15.0.2

Regards,
Samnang

**Comment by nilsbehlen** [comment]
Hi,
the problem is that privacyIDEA does not decode the @ sign which was encoded by the plugin starting v0.6. 
If you upgrade your privacyIDEA to at least 3.6 it will decode it properly.

**Comment by Samnang-An** [comment]
Thanks, nilsbehlen. Ill try to update server and report you back.

Regards,
Samnang

**Comment by Samnang-An** [comment]
Thanks, nilsbehlen. I upgraded server to 3.6.2 and it is working now. :1st_place_medal:
