### ISSUE TITLE
TOTP token enrolment from keycloack, first enter fails

### ISSUE THREAD

**Issue by arozmarin** [privacyidea/keycloak-provider#88]
Hi team,

I setup plugin as it was instructed, I'm able to enrol token but after enrolment if I put only token in I get response "Authentication failed. wrong otp pin", if I put in password+OTP it works ok, or if I refresh page I can enter only OTP and it worked ok. 

I also changed authentication policy in privacyidea "otppin to none", in this case I can enter only OTP and I won't get an error. But then I'll have problem login when I'm using radius proxy, ill get "Authentication failed. wrong otp pin". 

does anyone have solution for this that would be possible after token enrolment enter only OTP and not password+OTP, and not need to refresh webpage to work only OTP. 

thanks and regards
Ales

**Comment by nilsbehlen** [comment]
What is your policy regarding the PIN? This provider most probably works as intended, so i would guess it is a configuration problem.

**Comment by arozmarin** [comment]
Hi Nils,

Thank you for your replay, I think that is problem, I tried multiple different settings even separate authentication policies and nothing helped. 
I managed to make it work when I set "otppin to none" but then my radius 2FA authentication fails. Do you have any suggestion hot to set otppin, for enrolment or authentication or is there any other settings that I missed. 

thanks
Ales

**Comment by nilsbehlen** [comment]
Unfortunately, im not well versed with the configuration of the server. You could ask at the [community forum](https://community.privacyidea.org/) how to get your desired behavior.

**Comment by arozmarin** [comment]
Thanks Nils, I'll ask on forum
