### ISSUE TITLE
Update to Keycloak v 17.x  

### ISSUE THREAD

**Issue by itxworks** [privacyidea/keycloak-provider#89]
Is there a plan to upgrade the plugin to latest Keycloak?

Thx.

**Comment by nilsbehlen** [comment]
yes, i will start working on it today or tomorrow.

**Comment by nilsbehlen** [comment]
Hello again. I just tested it with keycloak 17 and it works for me as it is. Do you encounter any error when you are trying to use the provider?

**Comment by skinkie** [comment]
Works for me too.

**Comment by arozmarin** [comment]
Hi guys, sorry to ask a question but I tried privacyidea plugin on keycloack 17 and can't get it work. I copy plugin int different folders and no success. I tried in /lib/lib/main, lib/lib/deployment. Into which folder should I copy plugin to make it work?
thanks in advance and sorry to be annoying.
Oh yeah and which version to use latest or any older version?

**Comment by skinkie** [comment]
@arozmarin I really did no more than copy in the PrivacyIDEA-Provider.jar in /opt/keycloak/standalone/deployments and restarted the beast. Obviously after that you need to follow the manual to set up the 2FA login proces, but that has been well described.

**Comment by arozmarin** [comment]
@skinkie thanks for replay, but that work for keycloak and not for keycloak-X

**Comment by nilsbehlen** [comment]
Hi, there is a readme in the providers folder which states that you have to run `kc.bat build` after deploying new jars. Then you can `kc.bat start`.

**Comment by arozmarin** [comment]
Thanks Nils, 

I managed to make it work

**Comment by itxworks** [comment]
Hm sorry ... works with 18.0.0 too

**Comment by nilsbehlen** [comment]
oh wow, there is already v18. Thanks for lettings us now.
