### ISSUE TITLE
Remove theme enumeration in realm settings

### ISSUE THREAD

**Issue by skinkie** [privacyidea/keycloak-provider#91]
From the documentation it is mentioned that the PrivacyIDEA team should now be added by default. When selecting the privacyidea theme under Realm Settings / Themes my login page looks very boring and white. I don't see any 404's on missing css though.

![image](https://user-images.githubusercontent.com/502394/156665533-571c6b19-b27c-4f07-be1d-408d1ef976c9.png)

**Comment by nilsbehlen** [comment]
that is not what the theme is meant to be. it is the .ftl for the login page this provider displays.

**Comment by skinkie** [comment]
@nilsbehlen if it is not ment to be selected for the realm, why _can_ it be selected?
